services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-jansetu}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
      POSTGRES_DB: jansetu_db
    ports:
      - ${PORT:?}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
